name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install newman
      run: npm install -g newman
    - name: Build
      run: dotnet build --no-restore
    - name: TestSanity
      #run: dotnet test --no-build --verbosity normal
      run: dotnet test --filter Category=Sanity
    - name: TestSmoke
      run: dotnet test --filter Category=e2eAPI
    - name: Generate SpecFlow LivingDoc
      run: | # Will be useful to have consistent naming conventions for these directory parsings
        echo "Generating Acceptance Tests LivingDoc"
        ACCEPTANCE_TEST_PATH=$(find . -type d -iname "theatermenagementtest")
        echo "Full Path: " $ACCEPTANCE_TEST_PATH
        ACCEPTANCE_TEST_FOLDER=$(basename $ACCEPTANCE_TEST_PATH)
        echo "Folder Name: " $ACCEPTANCE_TEST_FOLDER
        ACCEPTANCE_TEST_DLL=$(find ./theatermenagementtest -type f -iname AcceptanceTest.dll -ipath "*/bin/*" -not -ipath "*/ref/*")
        echo "Test Assembly: " $ACCEPTANCE_TEST_DLL
        ACCEPTANCE_TEST_JSON=$(find $ACCEPTANCE_TEST_PATH -type f -iname "TestExecution.json" -ipath "*/bin/*" -not -ipath "*/ref/*")
        echo "Execution Json: " $ACCEPTANCE_TEST_JSON
        dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI
        livingdoc test-assembly $ACCEPTANCE_TEST_DLL -t $ACCEPTANCE_TEST_JSON
      shell: bash
    - name: 'Publish Specflow LivingDoc'
      uses: actions/upload-artifact@v2
      with:
        name: 'Specflow LivingDoc'
        path: LivingDoc.html
    # - name: Newman Action
    # run: | # Will be useful to have consistent naming conventions for these directory parsings
    #    echo "Generating Postman Tests "
    #    POSTMAN_PATH=$(find . -type d -iname "POSTMAN")
    #    echo "Full Path: " $POSTMAN_PATH
    #    cd $POSTMAN_PATH
    #    newman run theatermanagementcollection.postman_collection.json
    #  shell: bash
    - name: run child flow
      uses: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: FarukTurkusic-git
        repo: TestPipeline
        github_token: "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"
        github_user: FarukTurkusic-git
        workflow_file_name: blank.yml
        ref: release-branch
        wait_interval: 10
        inputs: '{}'
        propagate_failure: false
        trigger_workflow: true
        wait_workflow: true
